baseURL = "https://scienceacademy.github.io/web/"
languageCode = "en-us"
title = "Welcome to AP CSP"
theme = "hyde"
publishDir = "docs"

pygmentsStyle = "dracula"
pygmentsCodeFences = true

[params]
    themeColor = "theme-base-08"
    description = "Mr. Bradfield's AP Computer Science Principles"
    layoutReverse = false

[outputs]
    home = [ "HTML", "RSS", "JSON"]

[Menus]
	main = [
		{Name = "Your submit50 submissions", URL = "https://submit.cs50.io/"},
		{Name = "cs50 IDE", URL = "https://ide.cs50.io/"}
	]